name: docsbliss CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: build && deploy to surge.sh
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "16.x"
    - run: npm ci
    - run: npm run build
    - uses: dswistowski/surge-sh-action@v1
      with:
        domain: 'https://docsbliss.surge.sh'
        project: './out'
        login: ${{ secrets.SURGE_LOGIN }}
        token: ${{ secrets.SURGE_ACTK }}
